version: 0.2

cache:
  paths:
    - '/root/go/pkg/mod/**/*'
    - '/root/.cache/go-build/**/*'

phases:
  install:
    commands:
      - df -h
      - echo "=== INITIAL DISK USAGE ==="
      
  pre_build:
    commands:
      # Simulate cache bloat (remove this after testing)
      - chmod +x bloat-cache.sh
      - ./bloat-cache.sh
      - echo "=== AFTER CACHE BLOAT ==="
      - df -h
      
  build:
    commands:
      - go mod download
      - go build -o app main.go
      
  post_build:
    commands:
      - echo "=== FINAL DISK USAGE ==="
      - df -h
      - find /root/.cache/go-build -type f | wc -l || echo "Cache files count failed"
