version: 0.2

cache:
  paths:
    - '/root/go/pkg/mod/**/*'  # Go modules cache
    - '/root/.cache/go-build/**/*'  # Go build cache

phases:
  install:
    runtime-versions:
      golang: 1.24
      nodejs: 22
      python: 3.13
    commands:
      - docker system prune -af --volumes
      - apt-get clean || true
      - df -h
      
      # Configure Go environment and cache paths
      - echo "Setting up Go environment..."
      - go version
      - export GOMODCACHE=/root/go/pkg/mod
      - export GOCACHE=/root/.cache/go-build
      - export GOTMPDIR=/root/go-tmp
      - mkdir -p /root/go/pkg/mod /root/.cache/go-build $GOTMPDIR
      - echo "GOMODCACHE=/root/go/pkg/mod" >> /etc/environment
      - echo "GOCACHE=/root/.cache/go-build" >> /etc/environment
      - echo "GOTMPDIR=/root/go-tmp" >> /etc/environment
      
      # Setup Node.js environment  
      - echo "Setting up Node.js environment..."
      - node --version
      - npm --version
      - npm install -g yarn
      - yarn --version
      
      # Verify Python environment
      - echo "Setting up Python environment..."
      - python3 --version
      - which python3
  pre_build:
    commands:
      - echo "Cache paths configured for Go modules and build cache"
  build:
    commands:
      - echo "Build phase handled by GitHub Actions workflow"
  post_build:
    commands:
      - echo "Post-build phase complete"
